version: '3.0'
services:
  todoback:
    image: todobackend
    ports:
      - 3001:80
  todofront:
    image: todofrontend
    depends_on:
    - todoback
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_HOST=todoback
  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
    - todoback
    - todofront